import { AppColors } from '@/core/theme/app-colors';
import { fontTokens } from '@/core/theme/typography';
import { StyleSheet } from 'react-native';

export const font = {
  regular: fontTokens.fontFamily.regular,
  medium: fontTokens.fontFamily.medium,
  semiBold: 'Poppins_600SemiBold',
  bold: fontTokens.fontFamily.bold,
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: AppColors.background },
  scrollContent: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 24, gap: 14 },

  // DEV-only switcher
  caseSwitcher: { marginBottom: -4 },
  caseChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: AppColors.divider,
    marginRight: 8,
  },
  caseChipActive: { backgroundColor: AppColors.primary },
  caseChipText: { fontFamily: font.medium, fontSize: 10.5, color: AppColors.textSecondary },
  caseChipTextActive: { color: AppColors.white },

  // Order header
  orderHeaderCard: {
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: AppColors.border,
    backgroundColor: AppColors.surface,
  },
  orderHeaderTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  orderEyebrow: { fontFamily: font.semiBold, fontSize: 10.5, letterSpacing: 0.5, color: AppColors.textTertiary },
  orderTitle: { marginTop: 6, fontFamily: font.bold, fontSize: 18, color: AppColors.textPrimary },
  orderDate: { marginTop: 3, fontFamily: font.regular, fontSize: 12, color: AppColors.textSecondary },

  statusPill: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8 },
  statusPillText: { fontFamily: font.semiBold, fontSize: 11 },

  // Generic card
  card: {
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: AppColors.border,
    backgroundColor: AppColors.surface,
  },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 10 },
  sectionLabel: { fontFamily: font.semiBold, fontSize: 13, color: AppColors.textPrimary },
  helperText: { fontFamily: font.regular, fontSize: 11.5, color: AppColors.textTertiary, marginTop: 4 },
  emptyText: { fontFamily: font.regular, fontSize: 12, color: AppColors.textTertiary },

  // Pending
  pendingRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  pendingIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: AppColors.warningLight,
  },
  pendingText: { flex: 1, fontFamily: font.regular, fontSize: 12.5, lineHeight: 18, color: AppColors.textSecondary },

  // Offer card
  offerCard: {
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: AppColors.border,
    backgroundColor: AppColors.surface,
  },
  offerTopRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  offerAvatarWrap: { position: 'relative' },
  offerAvatar: { width: 46, height: 46, borderRadius: 14 },
  offerAvatarFallback: { alignItems: 'center', justifyContent: 'center', backgroundColor: AppColors.warningLight },
  offerAvatarFallbackText: { fontFamily: font.semiBold, fontSize: 16, color: AppColors.primaryDark },
  openDot: {
    position: 'absolute',
    right: -1,
    bottom: -1,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: AppColors.success,
    borderWidth: 2,
    borderColor: AppColors.surface,
  },
  offerName: { fontFamily: font.semiBold, fontSize: 13, color: AppColors.textPrimary },
  techBadgeRow: { flexDirection: 'row', gap: 6, marginTop: 3 },
  techBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: '#E6F4EA',
  },
  techBadgeText: { fontFamily: font.semiBold, fontSize: 9.5 },
  offerSkills: { marginTop: 4, fontFamily: font.regular, fontSize: 11, color: AppColors.textSecondary },
  offerMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  offerMetaText: { fontFamily: font.regular, fontSize: 10.5, color: AppColors.textTertiary },
  offerAmount: { fontFamily: font.bold, fontSize: 15, color: AppColors.textPrimary },

  offerToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: AppColors.divider,
  },
  offerToggleText: { fontFamily: font.semiBold, fontSize: 12, color: AppColors.primary },
  offerDetails: { marginTop: 10 },
  offerDetailsText: { fontFamily: font.regular, fontSize: 11.5, lineHeight: 17, color: AppColors.textSecondary },
  offerConfirmBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    height: 42,
    borderRadius: 12,
    marginTop: 12,
    backgroundColor: AppColors.primary,
  },
  offerConfirmBtnPressed: { backgroundColor: AppColors.primaryDark },
  offerConfirmBtnText: { fontFamily: font.semiBold, fontSize: 12.5, color: AppColors.white },

  // Technician assigned
  techRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  techAvatar: { width: 48, height: 48, borderRadius: 14 },
  techName: { fontFamily: font.semiBold, fontSize: 13.5, color: AppColors.textPrimary },

  phaseBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 14,
    padding: 10,
    borderRadius: 12,
    backgroundColor: AppColors.warningLight,
  },
  phaseBannerText: { fontFamily: font.medium, fontSize: 12, color: AppColors.primaryDark },

  // Additional quote
  additionalCard: { borderColor: AppColors.primaryLight, backgroundColor: AppColors.warningLight },
  additionalRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  additionalDesc: { fontFamily: font.medium, fontSize: 12.5, color: AppColors.textPrimary },
  additionalAmount: { marginTop: 3, fontFamily: font.bold, fontSize: 14, color: AppColors.textPrimary },
  additionalActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  additionalDeclineBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: AppColors.white,
    borderWidth: 1,
    borderColor: AppColors.border,
  },
  additionalConfirmBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    height: 34,
    borderRadius: 10,
    backgroundColor: AppColors.primary,
  },
  additionalConfirmBtnText: { fontFamily: font.semiBold, fontSize: 12, color: AppColors.white },

  // Hold / cancelled
  holdCard: { borderColor: '#F5C6C6', backgroundColor: '#FDE8E8' },
  holdReasonText: { fontFamily: font.regular, fontSize: 12.5, lineHeight: 18, color: AppColors.textSecondary },

  // OTP
  otpBox: {
    marginTop: 12,
    paddingVertical: 18,
    borderRadius: 14,
    alignItems: 'center',
    backgroundColor: AppColors.background,
    borderWidth: 1,
    borderColor: AppColors.border,
    borderStyle: 'dashed',
  },
  otpText: { fontFamily: font.bold, fontSize: 30, letterSpacing: 10, color: AppColors.textPrimary },
  otpWarning: { marginTop: 10, fontFamily: font.medium, fontSize: 11, color: AppColors.error, textAlign: 'center' },

  // Breakdown
  breakdownRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 6 },
  breakdownLabel: { flex: 1, fontFamily: font.regular, fontSize: 12.5, color: AppColors.textSecondary, marginRight: 8 },
  breakdownAmount: { fontFamily: font.semiBold, fontSize: 12.5, color: AppColors.textPrimary },
  breakdownTotalRow: { marginTop: 6, paddingTop: 10, borderTopWidth: 1, borderTopColor: AppColors.divider },
  breakdownTotalLabel: { fontFamily: font.semiBold, fontSize: 13, color: AppColors.textPrimary },
  breakdownTotalAmount: { fontFamily: font.bold, fontSize: 16, color: AppColors.textPrimary },

  // Review
  starRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  textArea: {
    minHeight: 72,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AppColors.border,
    backgroundColor: AppColors.background,
    padding: 12,
    fontFamily: font.medium,
    fontSize: 13,
    color: AppColors.textPrimary,
    textAlignVertical: 'top',
  },
  reviewSubmitBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 46,
    borderRadius: 12,
    marginTop: 12,
    backgroundColor: AppColors.primary,
  },
  reviewSubmitBtnText: { fontFamily: font.semiBold, fontSize: 13, color: AppColors.white },
  reviewSubmittedRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  reviewSubmittedText: { fontFamily: font.semiBold, fontSize: 13, color: AppColors.textPrimary },

  // Concern
  concernTypeRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
  concernTypeChip: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: AppColors.border,
    backgroundColor: AppColors.background,
  },
  concernTypeChipSelected: { backgroundColor: AppColors.primary, borderColor: AppColors.primary },
  concernTypeText: { fontFamily: font.medium, fontSize: 12, color: AppColors.textSecondary },
  concernTypeTextSelected: { color: AppColors.white },

  voiceRow: { marginTop: 12, flexDirection: 'row', alignItems: 'center', gap: 10, flexWrap: 'wrap' },
  recordBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: AppColors.primary,
  },
  recordBtnActive: { backgroundColor: AppColors.error },
  recordBtnText: { fontFamily: font.semiBold, fontSize: 12, color: AppColors.white },
  clipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: AppColors.background,
  },
  clipLabel: { fontFamily: font.medium, fontSize: 11.5, color: AppColors.textPrimary },

  // Footer (cancel)
  footer: {
    paddingHorizontal: 20,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: AppColors.border,
    backgroundColor: AppColors.surface,
  },
  cancelBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 48,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: AppColors.error,
  },
  cancelBtnText: { fontFamily: font.semiBold, fontSize: 13, color: AppColors.error },

  // Confirm modal
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
    paddingHorizontal: 24,
  },
  modalCard: {
    width: '100%',
    borderRadius: 20,
    padding: 22,
    backgroundColor: AppColors.white,
    alignItems: 'center',
  },
  modalIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: AppColors.warningLight,
    marginBottom: 12,
  },
  modalIconWrapDanger: { backgroundColor: '#FDE8E8' },
  modalTitle: { fontFamily: font.bold, fontSize: 16, color: AppColors.textPrimary, textAlign: 'center' },
  modalMessage: {
    marginTop: 8,
    fontFamily: font.regular,
    fontSize: 12.5,
    lineHeight: 18,
    color: AppColors.textSecondary,
    textAlign: 'center',
  },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 20, width: '100%' },
  modalBtnSecondary: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AppColors.border,
  },
  modalBtnSecondaryText: { fontFamily: font.semiBold, fontSize: 13, color: AppColors.textSecondary },
  modalBtnPrimary: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: 46,
    borderRadius: 12,
    backgroundColor: AppColors.primary,
  },
  modalBtnDanger: { backgroundColor: AppColors.error },
  modalBtnPrimaryText: { fontFamily: font.semiBold, fontSize: 13, color: AppColors.white },
});
